// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzeY-RNp6MncTA3vyjyyrJ6WJ81xAx3zo',
    appId: '1:120598379512:web:441bf9a1b487ad41eb740d',
    messagingSenderId: '120598379512',
    projectId: 'glamourstore-19f97',
    authDomain: 'glamourstore-19f97.firebaseapp.com',
    storageBucket: 'glamourstore-19f97.appspot.com',
    measurementId: 'G-T1HWD35PGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-sSrFg22hSrAt4Jk2xLnUWSK2addq-r4',
    appId: '1:120598379512:android:b506616e66b573a4eb740d',
    messagingSenderId: '120598379512',
    projectId: 'glamourstore-19f97',
    storageBucket: 'glamourstore-19f97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2PS51e1PuX6FWJYzPZlr9QbMhst1014',
    appId: '1:120598379512:ios:d359c66c59c0cd5aeb740d',
    messagingSenderId: '120598379512',
    projectId: 'glamourstore-19f97',
    storageBucket: 'glamourstore-19f97.appspot.com',
    iosBundleId: 'com.example.tiendaOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2PS51e1PuX6FWJYzPZlr9QbMhst1014',
    appId: '1:120598379512:ios:572ffc964ef9ab9feb740d',
    messagingSenderId: '120598379512',
    projectId: 'glamourstore-19f97',
    storageBucket: 'glamourstore-19f97.appspot.com',
    iosBundleId: 'com.example.tiendaOnline.RunnerTests',
  );
}
